/**
 * Task 3 + 5 gates as regression tests: ANI-2x analytic energy and forces vs
 * baked TorchANI references, and an aspirin FIRE relaxation.
 *
 * Reference values in test/fixtures/ani2x-references.json were generated by
 * spike/ani2x-onnx/gen_references.py using TorchANI ANI-2x
 * (periodic_table_index=True, float64): energy = model.energies (Ha), forces =
 * -dE/dcoords (Ha/Angstrom) via autograd. Regenerate with that script; no Python
 * is needed at test time.
 *
 * Gates: energy < 1e-5 Ha, max|dForce| < 1e-4 Ha/Angstrom, on water, methane,
 * aspirin, caffeine, cholesterol, peptide (129 atoms).
 */
import { describe, it, expect, beforeAll } from "vitest";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { Ani2xProvider } from "../src/potentials/ani2x/provider.js";
import { FireOptimizer } from "../src/optimize/fire.js";
import type { Molecule } from "../src/geometry/molecule.js";

const here = fileURLToPath(new URL(".", import.meta.url));
const modelDir = here + "../../../models/ani2x";
const refs = JSON.parse(readFileSync(here + "fixtures/ani2x-references.json", "utf8"));

function molOf(name: string): Molecule {
  const m = refs[name];
  return {
    symbols: m.symbols,
    positions: Float64Array.from(m.coords.flat() as number[]),
    charge: 0,
    multiplicity: 1,
  };
}

const names = ["water", "methane", "aspirin", "caffeine", "cholesterol", "peptide"];

describe("ANI-2x full-ensemble energy + force gates vs TorchANI", () => {
  let provider: Ani2xProvider;
  beforeAll(async () => {
    provider = await Ani2xProvider.create({ modelDir, variant: "full-f32" });
  });

  for (const name of names) {
    it(`${name}: energy < 1e-5 Ha, forces < 1e-4 Ha/A`, async () => {
      const mol = molOf(name);
      const { energy, forces } = await provider.energyForces(mol);
      const ref = refs[name];
      const dE = Math.abs(energy - ref.energy);
      const fRef = (ref.forces as number[][]).flat();
      let dF = 0;
      for (let k = 0; k < forces.length; k++) {
        dF = Math.max(dF, Math.abs(forces[k]! - fRef[k]!));
      }
      expect(dE, `dE=${dE.toExponential(3)}`).toBeLessThan(1e-5);
      expect(dF, `dF=${dF.toExponential(3)}`).toBeLessThan(1e-4);
    });
  }
});

describe("ANI-2x + FIRE optimizer", () => {
  it("relaxes aspirin into the spike's minimum basin", async () => {
    const provider = await Ani2xProvider.create({ modelDir, variant: "full-f32" });
    const mol = molOf("aspirin");
    // ANI forces are Ha/Angstrom; positions Angstrom. FIRE (momentum) reaches a
    // marginally deeper minimum than the spike's fixed-lr steepest descent: it
    // relaxes the RDKit conformer to ~-648.5344 Ha vs the spike's -648.5318 Ha
    // stop (max|F|=0.0196). So we assert convergence, energy monotone-ish below
    // the starting point, and E_final at least as relaxed as the spike value and
    // within 5e-3 Ha of it.
    const fire = new FireOptimizer({ forceTolerance: 0.02, maxSteps: 400, dtMax: 0.3 });
    const result = await fire.optimize(mol, provider);
    expect(result.converged).toBe(true);
    expect(result.energy).toBeLessThanOrEqual(-648.5318);
    expect(Math.abs(result.energy - -648.5318)).toBeLessThan(5e-3);
    expect(result.energy).toBeGreaterThan(-648.54); // sanity: same basin
  }, 60000);
});
