/**
 * RDKit-JS bridge: turn a SMILES string into a set of element symbols + a 3D
 * *seed* geometry the demo can then relax with ANI-2x.
 *
 * IMPORTANT — why this is not a pure "RDKit 3D" pipeline:
 * The npm `@rdkit/rdkit` MinimalLib (verified: version 2025.03.4) does NOT ship
 * the DistGeom/ETKDG 3D embedder. Every coordinate-generating entry point it
 * exposes (add_hs, set_new_coords, get_new_coords, get_mol with a details JSON)
 * produces a 2D depiction with all Z = 0 — the molblock is even tagged "2D".
 * There is no EmbedMolecule / generate_3d method on JSMol.
 *
 * So RDKit is used for what it CAN do correctly and instantly: parse the SMILES,
 * perceive valence, and add explicit hydrogens with a sane 2D layout (distinct
 * X/Y per atom, correct connectivity). We then break planarity with a small
 * deterministic Z displacement so the (otherwise reflection-symmetric) ANI-2x
 * forces perpendicular to the plane are non-zero, and hand that seed to the
 * ANI-2x + FIRE optimizer in the worker. The optimizer produces the genuine 3D
 * geometry — a real energy minimum (verified: aspirin from SMILES relaxes to
 * -648.52 Ha, within ~7 kcal/mol of the baked reference minimum). The displayed
 * structure is therefore truly 3D, generated by ANI-2x, not a flattened 2D fake.
 */

/** Elements ANI-2x is trained on. Anything else -> no meaningful energy. */
export const ANI2X_ELEMENTS = new Set(["H", "C", "N", "O", "F", "S", "Cl"]);

export interface SmilesSeed {
  /** element symbols, one per atom */
  symbols: string[];
  /** flat [x0,y0,z0,...] Angstrom seed geometry (planarity-broken 2D) */
  positions: number[];
  /** elements present that ANI-2x does not cover (empty if all supported) */
  unsupported: string[];
  /** canonical SMILES echoed back by RDKit (for the readout) */
  canonicalSmiles: string;
}

// ---------------------------------------------------------------------------
// Minimal typing for the MinimalLib surface we use (the shipped .d.ts lags the
// wasm; we only touch these members).
// ---------------------------------------------------------------------------
interface JSMol {
  is_valid(): boolean;
  get_num_atoms(): number;
  get_smiles(): string;
  add_hs(): string; // returns a V2000 molblock WITH explicit Hs
  delete(): void;
}
interface RDKitModule {
  get_mol(smiles: string): JSMol | null;
  version(): string;
}
type RDKitLoader = (opts?: { locateFile?: () => string }) => Promise<RDKitModule>;

declare global {
  interface Window {
    initRDKitModule?: RDKitLoader;
  }
}

// The dist assets are served at /rdkit/* by a small dev middleware in
// vite.config.ts (mirrors the existing /models/* middleware) so we neither
// duplicate the ~7 MB wasm into public/ nor commit it.
const RDKIT_JS_URL = "/rdkit/RDKit_minimal.js";
const RDKIT_WASM_URL = "/rdkit/RDKit_minimal.wasm";

let rdkitPromise: Promise<RDKitModule> | undefined;

/** Lazily load the RDKit MinimalLib (wasm is ~7 MB — only fetched on first use). */
export function loadRDKit(): Promise<RDKitModule> {
  if (rdkitPromise) return rdkitPromise;
  rdkitPromise = (async () => {
    if (!window.initRDKitModule) {
      await new Promise<void>((resolve, reject) => {
        const s = document.createElement("script");
        s.src = RDKIT_JS_URL;
        s.onload = () => resolve();
        s.onerror = () => reject(new Error(`failed to load ${RDKIT_JS_URL}`));
        document.head.appendChild(s);
      });
    }
    if (!window.initRDKitModule) throw new Error("initRDKitModule missing after script load");
    return window.initRDKitModule({ locateFile: () => RDKIT_WASM_URL });
  })();
  return rdkitPromise;
}

/** Report the loaded RDKit version (for the readout); loads it if needed. */
export async function rdkitVersion(): Promise<string> {
  return (await loadRDKit()).version();
}

/**
 * Parse a V2000 molblock's atom block into symbols + flat Angstrom coords.
 * Uses fixed-column slicing (V2000 is column-oriented): x[0:10] y[10:20]
 * z[20:30], element symbol at [31:34]. Handles 2-char symbols (Cl) correctly.
 */
function parseMolblock(mb: string): { symbols: string[]; positions: number[] } {
  const lines = mb.split("\n");
  const counts = lines[3];
  if (!counts) throw new Error("malformed molblock (no counts line)");
  const nAtoms = parseInt(counts.slice(0, 3), 10);
  if (!Number.isFinite(nAtoms) || nAtoms <= 0) throw new Error("molblock has no atoms");
  const symbols: string[] = [];
  const positions: number[] = [];
  for (let i = 0; i < nAtoms; i++) {
    const l = lines[4 + i];
    if (l === undefined) throw new Error("molblock truncated");
    const x = parseFloat(l.slice(0, 10));
    const y = parseFloat(l.slice(10, 20));
    const z = parseFloat(l.slice(20, 30));
    const sym = l.slice(31, 34).trim();
    symbols.push(sym);
    positions.push(x, y, z);
  }
  return { symbols, positions };
}

/**
 * Deterministic planarity-breaking jitter. A perfectly planar molecule sits at
 * a reflection-symmetric point where ANI-2x's perpendicular force is exactly
 * zero, so FIRE would never pucker it. A small pseudo-random Z (plus a tiny
 * X/Y nudge) gives the optimizer a gradient to descend. Seeded for reproducible
 * loads.
 */
function breakPlanarity(positions: number[]): void {
  let a = 0x9e3779b9 >>> 0;
  const rng = (): number => {
    a = (Math.imul(a, 1664525) + 1013904223) >>> 0;
    return a / 4294967296;
  };
  const n = positions.length / 3;
  for (let i = 0; i < n; i++) {
    positions[3 * i] = positions[3 * i]! + (rng() * 2 - 1) * 0.05;
    positions[3 * i + 1] = positions[3 * i + 1]! + (rng() * 2 - 1) * 0.05;
    positions[3 * i + 2] = positions[3 * i + 2]! + (rng() * 2 - 1) * 0.6;
  }
}

/**
 * SMILES -> element symbols + 3D seed geometry.
 * Throws on an unparseable SMILES (caller shows a friendly message).
 * On success `unsupported` lists any elements ANI-2x can't handle; the caller
 * still displays the structure but must disable Optimize in that case.
 */
export async function smilesToSeed(smiles: string): Promise<SmilesSeed> {
  const trimmed = smiles.trim();
  if (!trimmed) throw new Error("empty SMILES");
  const RDKit = await loadRDKit();
  const mol = RDKit.get_mol(trimmed);
  if (!mol) throw new Error("could not parse SMILES");
  try {
    if (!mol.is_valid() || mol.get_num_atoms() === 0) {
      throw new Error("SMILES parsed to an empty/invalid molecule");
    }
    const canonicalSmiles = mol.get_smiles();
    const molblock = mol.add_hs(); // explicit Hs + a 2D layout
    const { symbols, positions } = parseMolblock(molblock);
    breakPlanarity(positions);
    const unsupported = [...new Set(symbols.filter((s) => !ANI2X_ELEMENTS.has(s)))];
    return { symbols, positions, unsupported, canonicalSmiles };
  } finally {
    mol.delete();
  }
}

/** Curated example SMILES that stay within ANI-2x's element set. */
export const SMILES_EXAMPLES: { name: string; smiles: string }[] = [
  { name: "ethanol", smiles: "CCO" },
  { name: "benzene", smiles: "c1ccccc1" },
  { name: "acetic acid", smiles: "CC(=O)O" },
  { name: "aspirin", smiles: "CC(=O)Oc1ccccc1C(=O)O" },
  { name: "caffeine", smiles: "CN1C=NC2=C1C(=O)N(C(=O)N2C)C" },
  { name: "paracetamol", smiles: "CC(=O)Nc1ccc(O)cc1" },
  { name: "glycine", smiles: "C(C(=O)O)N" },
  { name: "thiophene", smiles: "c1ccsc1" },
  { name: "fluorobenzene", smiles: "c1ccccc1F" },
];
